openapi: 3.0.0
servers: [
  {
  'url': '/',
  "description": "",
  }
]
info:
  description: This is a simple Travel App API
  version: "1.0.0"
  title: Travel App Demo API

paths:
  /countries:
    get:
      tags:
        - countries
      summary: list of countries
      parameters:
        - in: query
          name: lang
          description: optional language
          required: false
          schema:
            type: string
      responses:
        '200':
          description: list of all countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
  /countries/{countryId}:
    get:
      tags:
        - countries
      summary: country details by id
      parameters:
        - in: path
          name: countryId
          required: true
          schema:
            type: string
            format: objectId  
        - in: query
          name: lang
          description: optional language
          required: false
          schema:
            type: string
      responses:
        '200':
          description: country and array of places related to her
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Country'
                  - type: object
                    properties:
                      places:
                        type: array
                        items:
                          type: object
                          properties:
                            photoUrl:
                              type: string
                            localizations:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    description:
                                      type: string
        '404':
          description: country not found
        '400':
          description: 'invalid Country ID. ID must be objectID'
    post:
      tags:
        - rating
      summary: create new rating for place
      parameters:
        - in: path
          name: countryId
          required: true
          schema:
            $ref: '#/components/schemas/Rating'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                placeId:
                  type: string
                  description: The place's id
                userId:
                  type: string
                  description: The user's id
                rating:
                  type: integer
                  description: The place's rating
              required:
                - placeId
                - userId
                - rating
      responses:
        '200':
          description: The rating has been added
        '400':
          description: 'Bad request'
components:
  schemas:
    Country:
      type: object
      required:
        - currency
        - ISOCode
        - capitalLocation
        - coordinates

      properties:
        id:
          type: string
          format: objectId
          example: 60250368d342c8267c02a558
        imageUrl:
          type: string
          example: www.example.com/example.jpg
        videoUrl:
          type: string
          example: www.example.com/example.mp4
        ISOCode:
          type: string
          example: US
        capitalLocation:
          type: object
          properties:
            coordinates:
              type: array
              items:
                type: number
            type:
              type: string
              enum: [Point]
        localizations:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              capital: 
                type: string
              description:
                type: string
    Place:
      type: object
      required:
        - countryId
        - photoUrl
      properties:
        countryId: 
          type: string
          format: objectId
        photoUrl:
          type: string
        localizations:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
    Rating:
      type: object
      required:
          - placeId
          - userId
          - rating
      properties:
        placeId: 
          type: string
          format: objectId
        userId:
          type: string
          format: objectId
        rating:
          type: integer
          minimum: 0
          maximum: 5